apiVersion: batch/v1
kind: Job
metadata:
  name: {{JOB_NAME}}-builder
spec:
  template:
    spec:
      containers:
      - name: builder
        image: {{BUILDER_IMAGE}}
        command: ["echo", "Building project: {{PROJECT_NAME}}"]
        env:
        - name: PROJECT_NAME
          value: "{{PROJECT_NAME}}"
        - name: GCP_PATH
          value: "{{GCP_PATH}}"
      restartPolicy: Never
  backoffLimit: 3