apiVersion: batch/v1
kind: Job
metadata:
  name: yaml-test-job
spec:
  template:
    spec:
      containers:
        - name: test-container
          image: bash:latest
          command: ["echo", "Hello from YAML!"]
      restartPolicy: Never
  backoffLimit: 2
